name: biasnet
dependencies:
 - rdkit::rdkit>=2018.03
 - pip
 - pip:
    - hypopt
    - argparse
    - tqdm
    - xgboost==0.90
    - matplotlib==3.1.1
    - seaborn==0.9.0
    - scikit-learn==0.22.1
    - joblib

